# Generated by Django 5.1.4 on 2025-01-13 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_task_assign_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority_level',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
